services:
  app:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: financing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password